<?php
$escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Data Repository Connector'), 1, $this->translate('Past Imports')); ?>
<?php if(empty($imports)): ?>
<div class="no-resources">
    <p><?php echo $this->translate('There are no past imports.'); ?></p>
</div>
<?php else: ?>
<?php echo $this->pagination(); ?>

<form method='POST'>
    <fieldset id='page-actions'>
        <input type='submit' value="<?php echo $this->translate('Submit'); ?>" />
    </fieldset>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $escape($this->translate('Undo'));?></th>
                <th><?php echo $escape($this->translate('Re-run'));?></th>
                <th><?php echo $this->sortLink($this->translate('Job ID'), 'id');?></th>
                <th><?php echo $escape($this->translate('Data repository link'));?></th>
                <th><?php echo $escape($this->translate('Comment'));?></th>
                <th><?php echo $escape($this->translate('Items'));?></th>
                <th><?php echo $escape($this->translate('Date'));?></th>
                <th><?php echo $escape($this->translate('Status'));?></th>
                <th><?php echo $escape($this->translate('Owner'));?></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($imports as $import): ?>
        <?php $job = $import->job(); ?>
        <?php $undoJob = $import->undoJob(); ?>
        <?php $rerunJob = $import->rerunJob(); ?>
        <tr class="<?php echo isset($undone) ? 'undone' : ''; ?>" >
            <td><input type='checkbox' name='undoJobs[]' value='<?php echo $job->id(); ?>' aria-label="<?php echo $this->translate('Undo job'); ?>" />
            <td><input type='checkbox' name='rerunJobs[]' value='<?php echo $job->id(); ?>' aria-label="<?php echo $this->translate('Re-run job'); ?>" />
            <td><?php echo $job->link($job->id()); ?></td>
            <td>
                <?php $args = $job->args();
                if (isset($args['collection_link'])) {
                    echo $this->hyperlink($args['data_repo_service'], $args['collection_link']);
                } else {
                    echo $this->hyperlink($args['data_repo_service'], $args['main_uri']);
                }
                ?>
            </td>
            <td>
                <?php echo $import->comment(); ?>
            </td>
            <td>
            <?php
            if ($rerunJob) {
                $linkID = $rerunJob->id();
            } else {
                $linkID = $job->id();
            }
            if ($import->addedCount() > 0 && !$undoJob) {
                echo $this->hyperlink('Added: ' . $import->addedCount(), $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['data_import_id' => $linkID]])) . ' ';
            } else {
                echo 'Added: ' . $import->addedCount() . ' ';
            }
            if ($import->updatedCount() > 0 && !$undoJob) {
                echo $this->hyperlink('Updated: ' . $import->updatedCount(), $this->url('admin/default', ['controller' => 'item', 'action' => 'browse'], ['query' => ['data_import_id' => $linkID]]));
            } else {
                echo 'Updated: ' . $import->updatedCount();
            }
            ?>
            </td>
            <td><?php echo $escape($this->i18n()->dateFormat($job->started())); ?></td>
            <td>
            <?php
            if ($rerunJob) {
                $status = $this->translate('Reran in job ') . $rerunJob->id() . ': ' . $escape($this->i18n()->dateFormat($rerunJob->ended()));
            } else if ($undoJob) {
                $status = $this->translate('Undone: ') . ' ' . $escape($this->i18n()->dateFormat($undoJob->ended()));
            } else {
                $status = $this->translate($job->status());
            } 
            ?>
            <?php echo $status; ?>
            </td>
            <td><?php echo $this->hyperlink($job->owner()->name(), $this->url('admin/id', array('controller' => 'user', 'action' => 'show', 'id' => $job->owner()->id()))); ?></td>
        </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</form>
<?php endif; ?>
